power <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
february <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
power$Time <- strptime(power$Time, "%H:%M:%S")
x <- paste(february$Date,february$Time)
february$Date <- strptime(x, "%d/%m/%Y %H:%M:%S")
february$Sub_metering_1 <- as.numeric(as.character(february$Sub_metering_1))
february$Sub_metering_2 <- as.numeric(as.character(february$Sub_metering_2))
february$Sub_metering_3 <- as.numeric(as.character(february$Sub_metering_3))
february <- subset(february, select=-c(Time))
png("plot3.png", width=480px, height=480px)
plot(february$Date,february$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(february$Date,february$Sub_metering_1)
lines(february$Date,february$Sub_metering_2,col="red")
lines(february$Date,february$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"))
dev.off()