power <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
february <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
power$Time <- strptime(power$Time, "%H:%M:%S")
x <- paste(february$Date,february$Time)
february$Date <- strptime(x, "%d/%m/%Y %H:%M:%S")
february$Global_active_power <- as.numeric(as.character(february$Global_active_power))
february <- subset(february, select=-c(Time))
png("plot2.png", width=480px, height=480px)
plot(february$Date,february$Global_active_power,type="n",xlab="",ylab="Global Active Power (kilowatts)")
lines(february$Date,february$Global_active_power)
dev.off()